settings:
  interval: 3600
  timeout: 1000
  slurmdir: /usr/local/slurm/bin/
  logging:
    level: debug
    dir:
  prometheus:
    port: 8000
    enable: true

nodeLists:
  hydraCompute:
    nodeNames: hydra[01-36]
  tesla:
    nodeNames: tesla

tests:
  - name: Succeedscript
    script:
      path: ./testscripts/succeedscript.sh

  - name: Failscript
    script:
      path: ./testscripts/failscript.sh

  - name: Time-Synchronization
    slurmScript:
      path: testscripts/datetest.sh
      nodeLists: hydraCompute
    conditions:
      difference: 150000000

  - name: Memory Bandwidth
    slurmScript:
      path: testscripts/memory_bandwith.sh
      nodeLists: hydraCompute
      options:
        - -c32
    conditions:
      min: 110000

  - name: Command
    command: "true"

  - name: Min-Tests
    command: echo 10
    conditions:
      min: 15

  - name: Max-Test
    command: echo 30
    conditions:
      max: 15

  - name: Omnipath Network Bandwidth
  slurmPairScript:
    path: testscripts/omnibandwith.sh
    nodeLists: hydraCompute
    pairSize: 2
    options:
      - -mblock:cyclic
      - -N2
      - --ntasks-per-node=2
  conditions:
    min: 20000

  - name: Multiline test
    slurmScript:
      path: testscripts/multilinetest.sh
      nodeLists: hydraCompute
    conditions:
      - min: 10
        max: 10
      - min: 1000
      - maxDifference: 100