# example clustok config
# located usually in: '/etc/clustok/config.yml'

# general settings
settings:
  # wait times between tests (only used with option -r/--repeat)
  interval: 3600
  timeout: 1000
  # slurm options
  slurm:
    # directory of the slurm binaries
    dir: /usr/local/slurm/bin/
    # Optional: a specific partition to run on
    partition: q_staff
    # Optional: arguments to always pass to srun
    args:
      - --comment="clustok job"
  # write log to a file
  output:
    # directory/fileName of the log file
    dir: /var/log/clustok
    fileName: "test-%Y-%m-%d-%H"
    format: json # pretty/json
  # or write the log to the console
  #output:
  #  console
  logging:
    # base verbosity level
    level: WARN    # DEBUG/INFO/WARN/ERROR/CRITICAL
  # if and on which port to export prometheus statistics
  prometheus:
    enable: true
    port: 8000

# nodes that slurm-tests should run on
# (command-/script-tests always run on the machine that runs clustok)
nodeLists:
  hydraCompute:
    nodeNames: hydra[01-5]

# the tests to run:
tests:
  # test can be of type: command, script, slurmScript or slurmPairScript
  # different types support different options (see below)

  - name: Command Test
    # Optional:
    descr: An optional description
    command: "echo 6"
    # Optional: set conditions that the output should follow 
    # (can be int or float)
    conditions:
      min: 5
      max: 7

  - name: Script Test
    descr: Executes a script
    script:
      # path to the script
      path: ./testscripts/succeedscript.sh
    # also supports the conditions min/max

  - name: Slurm Script Test
    descr: Runs the script via slurm
    slurmScript:
      path: ./testscripts/multilinetest.sh
      # on which nodes to run
      nodeLists: hydraCompute
      # Optional: a list of options to pass to slurm
      options:
        - -c32
    # supports the conditions min/max/difference
    
  - name: Slurm Pair Script Test
    descr: Network latency between two pairs of nodes
    slurmPairScript:
      path: ./testscripts/datetest.sh
      nodeLists: hydraCompute
      # how many nodes to use at the same time
      pairSize: 2
      options:
        - --ntasks-per-node=1
    # supports the conditions min/max/difference
