[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clustok"
version = "0.2.1"
description = "A python tool to run and evaluate different types of tests on clusters"
readme = "README.md"
authors = [
    {name = "Markus Hinkel"},
    {name = "Elia Nitsche"},
    {email = "elia.nitsche@tuwien.ac.at"}
]
maintainers = [
    {name = "Elia Nitsche", email = "elia.nitsche@tuwien.ac.at"},
]
requires-python = ">=3.9"
dependencies = [
    "fire",
    "pyyaml",
    "psutil",
    "schema",
	"prometheus-client>=0.12.0",
]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://hellogity.par.tuwien.ac.at/sysadmin/clustok"
Repository = "https://hellogity.par.tuwien.ac.at/sysadmin/clustok"

[project.scripts]
clustok = "clustok:main"

# unit test
[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test_*"]
python_functions = ["test_*"]

[project.optional-dependencies]
test = [
	"pytest>=8.0",
	"pytest-subprocess",
	"pytest-mypy", "types-PyYAML", "types-requests",
	"requests",
]

# type checking
[tool.mypy]
ignore_missing_imports = true
files = ["src"]
exclude = [
	"build/",
	"dist/",
	".*/build/.*",
	".*/dist/.*",
]
