[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clustok"
version = "0.2.0"
description = "A python tool to run and evaluate different types of tests on clusters"
readme = "README.md"
authors = [
    {name = "Markus Hinkel"},
    {name = "Elia Nitsche"},
    {email = "elia.nitsche@tuwien.ac.at"}
]
maintainers = [
    {name = "Elia Nitsche", email = "elia.nitsche@tuwien.ac.at"},
]
requires-python = ">=3.7"
dependencies = [
    "fire",
    "pyyaml",
    "psutil",
    "schema",
	"prometheus-client>=0.12.0",
]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://hellogity.par.tuwien.ac.at/sysadmin/clustok"
Repository = "https://hellogity.par.tuwien.ac.at/sysadmin/clustok"

[project.scripts]
clustok = "clustok:main"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
