#!python

import time
from typing import List
import fire
import logging

from interfaces.runner import Runner
from interfaces.exporter import Exporter

from utils.configManager import Config
from utils.customLogger import CustomLogger
from testRunner import TestRunner

from prometheus_client import start_http_server
from prometheus_client.core import GaugeMetricFamily, REGISTRY, CounterMetricFamily

from exporter.prometheusExporter import PrometheusExporter
from exporter.fileExporter import FileExporter
from testEvaluator import TestEvaluator

def main(config, repeat=False, prometheus=False, v=False, vv=False, outFile=None):
  exporters: List[Exporter] = []
  runners: List[Runner] = []
  
  # Setup Logger
  logger = CustomLogger('[ClustOK]')

  if (v):
    logger.setLevel(logging.INFO)

  if (vv):
    logger.setLevel(logging.DEBUG)

  # Load Config
  config = Config(logger, config)

  evaluator = TestEvaluator(logger, config)
  runners.append(TestRunner(logger, config))

  if (prometheus):
    exporters.append(PrometheusExporter.init(logger, config))

  if (outFile is not None):
    exporters.append(FileExporter.init(outFile))

  # Main Loop
  while True:
    results = {}
    for runner in runners:
      results.update(runner.execute())
      
    # Update exporters
    for exporter in exporters:
         exporter.update(results)

    if (repeat == False):
      break
    
    logger.info("Waiting %d seconds", config.interval)
    time.sleep(config.interval)


if __name__ == '__main__':
    fire.Fire(main)