#!/usr/bin/python

import time
from typing import List
import fire
import logging


# Runner
from interfaces.runner import Runner
from runner.localRunner import LocalTestRunner
from runner.slurmRunner import SlurmTestRunner

from interfaces.exporter import Exporter
from interfaces.evaluator import Evaluator

from utils.config.configManager import ConfigManager
from utils.logger.customLogger import CustomLogger

from prometheus_client import start_http_server
from prometheus_client.core import GaugeMetricFamily, REGISTRY, CounterMetricFamily

from exporter.prometheusExporter import PrometheusExporter
from exporter.fileExporter import FileExporter
from exporter.consoleExporter import ConsoleExporter

def main(config="/etc/clustOK/config.yml", repeat=False, v=False, vv=False):
  exporters: List[Exporter] = []
  runners: List[Runner] = []
  evaluators: List[Evaluator] = []
  
  # Setup Logger
  logger = CustomLogger('[ClustOK]')

  if (v):
    logger.setLevel(logging.INFO)

  elif (vv):
    logger.setLevel(logging.DEBUG)

  # Load Config
  configManager = ConfigManager(logger, config)
  config = configManager.config
  settings = config.settings

  if (not v and not vv):
    logger.setLevel(settings.logging.level)

  #evaluator = TestEvaluator(logger, config)
  runners.append(LocalTestRunner(logger, config))
  runners.append(SlurmTestRunner(logger, config))

  if (config.settings.prometheus.enable):
    exporters.append(PrometheusExporter.init(logger, config))

  if (config.settings.output == "console"):
    exporters.append(ConsoleExporter.init(settings.output))

  elif (config.settings.output is not None):
    exporters.append(FileExporter.init(settings.output))

  # Main Loop
  while True:
    results: dict = {}

    # Execute tests
    for runner in runners:
      result = runner.execute()

      # Collect results
      for singleResult in result:
        if singleResult["name"] not in results:
          results[singleResult["name"]] = []

        results[singleResult["name"]].append(singleResult)
      
    for _,resultList in results.items():
      resultList.sort(key=lambda result: result["nodes"])


    # Evaluate results
    for evaluator in evaluators:
      evaluator.evaluate(results)

    # Update exporters
    for exporter in exporters:
      exporter.update(results)
  
    if (repeat == False):
      break
  
    logger.info("Waiting %d seconds", config.settings.interval)
    time.sleep(config.settings.interval)

  for exporter in exporters:
    exporter.destroy()

if __name__ == '__main__':
    fire.Fire(main)