#!python

from time import time
import fire
import logging

from configManager import Config
from customLogger import CustomLogger
from testRunner import TestRunner

def main(config, repeat=False, v=False, vv=False):
  # Setup Logger
  logger = CustomLogger('[ClustOK]')

  if (v):
    logger.setLevel(logging.INFO)

  if (vv):
    logger.setLevel(logging.DEBUG)

  # Load Config
  config = Config(logger, config)

  testRunner = TestRunner(logger, config)

  while True:
    testRunner.executeTests()
    if (repeat == False):
      break
    logger.debug("Waiting %d seconds", config.interval)
    time.sleep(config.interval)

if __name__ == '__main__':
    fire.Fire(main)